### ISSUE TITLE
method names are case insensitive

### ISSUE THREAD

**Issue by krakjoe** [paragonie/stern#1]
https://github.com/paragonie/stern/blob/master/src/SternTrait.php#L19

`$candidates` and related code is not necessary; Case is ignored by `method_exists` (method names are case insensitive).

**Comment by kelunik** [comment]
That's already fixed.

**Comment by krakjoe** [comment]
Yeah, fixed by yourself in 8d302df8946eb91a2ea1fc1c9142a5ac8b9edffa

**Comment by kelunik** [comment]
Yes, more a reminder for @paragonie-scott to close the issue. :-)
